/**
 * Represents the result of an assertion test, containing details about the test outcome.
 *
 * @remarks
 * This interface defines the structure for assertion results that provide detailed information
 * about test outcomes. It includes standard fields like pass/fail status, expected and received
 * values, and custom messages, while also allowing for additional custom properties through
 * an index signature.
 *
 * Assertion results are typically generated by matcher functions during test execution and
 * can be attached to xJetError instances to provide rich context about failures.
 * Test reporters and frameworks can use this structured information to generate detailed
 * failure reports with helpful visualizations of the differences between expected and
 * actual values.
 *
 * @example
 * ```ts
 * // Creating a basic assertion result
 * const result: AssertionResultInterface = {
 *   name: 'toBe',
 *   pass: false,
 *   actual: 41
 *   message: 'Expected value to equal 42',
 *   expected: 42,
 * };
 *
 * // With custom properties for specific matchers
 * const arrayResult: AssertionResultInterface = {
 *   name: 'toContain',
 *   pass: false,
 *   actual: ['apple', 'orange'],
 *   message: 'Expected array to contain item',
 *   expected: 'banana',
 *   matcherHint: 'toContain',
 *   printExpected: 'banana',
 *   printReceived: '["apple", "orange"]'
 * };
 * ```
 *
 * @see AssertionError - The error class that may contain this result information
 *
 * @since 1.0.0
 */

export interface AssertionResultInterface {
    name?: string;
    pass?: boolean;
    actual?: unknown;
    message?: string;
    expected?: unknown;
    [key: string]: unknown;
}

export interface OptionsExpectErrorInterface {
    name?: string;
    info?: Array<string>;
    params?: Array<string>;
    hintChain: Array<string>;
    hintLabel?: string;
    assertion?: AssertionResultInterface;
}
